kernel:
    resource: ../../src/Kernel.php
    type: annotation

customer_controllers:
    resource: ../../src/Customer/Adapter/Framework/Http/Controller/
    type: annotation
    prefix: /api/customers

user_controllers:
    resource: ../../src/User/Adapter/Framework/Http/Controller/
    type: annotation
    prefix: /api/users


